[package]
name = "callandor"
version = "0.1.0"
edition = "2024"

[dependencies]
pollster = "0.4.0"
wgpu = { version = "27.0.1", features = ["spirv"] }
winit = "0.30.12"

[build-dependencies]
shaderc = "0.10.1"
